# Server params
serverPort: 8080
publicDir: public

# Indexer params
indexDir: index
stopWord: data/stopWords.txt
stopWordSize : 779
resultSize: 1000

# Default page
wlecomePages:
  - index.html
  - default.html

# AWS params
awsAccessKeyId: AKIAI4G5OARPTHUJYJMA
awsSecretKey: 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
awsEndPoint: webservices.amazon.com

# YouTuBe params
youtubeApiKey: AIzaSyBQXg30E9SWTTl8xFjFJoayFYDJyjc_JGk

# OverStock Query Url
overStockUrl: http://www.overstock.com/search?keywords=%s

# Twitter params
twitterConsumerKey: xtrOvOmrFzg4CWIpkhkP6PkNL
twitterSecretKey: cCzpYkApxMvN44y1MvAs7pq6qOSZoGXsqHIUOZcWeOsjf8jmBJ
twitterAccessToken: 279284725-NhVkm1HC4BTjK2WY31eK1h77uKxIA4bXvw3G2tPO
twitterAccessTokenSecert: UdBKLwXwfmjEKo5gruOd0IleR6La79G96VGgU9jFgLKFi

# Crawlers
crawlers:
  - ir.crawler.amazon.AWSCrawler
  - ir.crawler.overstock.OverstockCrawler

# Real-time
realTimeCrawlers:
  - className: ir.crawler.youtube.YouTubeCrawler
    type: YOUTUBE
  - className: ir.crawler.twitter.TwitterCrawler
    type: TWITTER

# Servlets
servlets:
  - className: ir.servlets.Search
    contextPath: /search
  - className: ir.servlets.Training
    contextPath: /training
