# Server params
serverPort: 8080
publicDir: public

# Default page
wlecomePages:
  - index.html
  - default.html

# AWS params
awsAccessKeyId: AKIAI4G5OARPTHUJYJMA
awsSecretKey: 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
awsEndPoint: webservices.amazon.com

# YouTuBe params
youtubeApiKey: AIzaSyBQXg30E9SWTTl8xFjFJoayFYDJyjc_JGk

# OverStock Query Url
overStockUrl: http://www.overstock.com/search?keywords=%s
# Crawlers
crawlers:
  - ir.crawler.amazon.AWSCrawler
  - ir.crawler.youtube.YouTubeCrawler

# Servlets
servlets:
  - className: ir.servlets.Search
    contextPath: /search
  - className: ir.servlets.Training
    contextPath: /training